[package]
name = "word-tool"
version = "0.1.0"
authors = ["Matthew Ashton Knochel <matthewashtonknochel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
orbtk = "0.3.1-alpha3"
grep = "0.2.7"
